# Generated by Django 2.2.4 on 2019-08-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190823_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='idEquipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Equipamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='idPessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='idModelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='idTipoEquipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TipoEquipamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamentosemprestimo',
            name='idEmprestimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Emprestimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamentosemprestimo',
            name='idEquipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Equipamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='idMarca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='idArmario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Armario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='idPessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataHoraDevolucao',
            field=models.DateTimeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataHoraEmprestismo',
            field=models.DateTimeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='previsaoDevolucao',
            field=models.DateTimeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='equipamentosemprestimo',
            name='emprestado',
            field=models.BooleanField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataHoraFinal',
            field=models.DateTimeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataHoraInicial',
            field=models.DateTimeField(max_length=45),
        ),
    ]
